sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"

services:
  - docker

before_install:
  - docker pull redis:alpine
  - docker run -p 6379:6379 -d redis:alpine

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls